/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug */
        get: operations["debug_api_v1_debug_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/terms-accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Terms */
        post: operations["accept_terms_api_v1_auth_terms_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Contact */
        post: operations["send_contact_api_v1_contact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_admin_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_v1_admin_settings_patch"];
        trace?: never;
    };
    "/api/v1/admin/settings/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Settings
         * @description No auth — used by Impressum, AGB, Datenschutz pages.
         */
        get: operations["get_public_settings_api_v1_admin_settings_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User Role */
        patch: operations["update_user_role_api_v1_admin_users__user_id__role_patch"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deactivate User */
        delete: operations["deactivate_user_api_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Log */
        get: operations["get_audit_log_api_v1_admin_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notifications */
        get: operations["get_notifications_api_v1_admin_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notification Read */
        post: operations["mark_notification_read_api_v1_admin_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/erp/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Erp Records */
        get: operations["list_erp_records_api_v1_erp_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/erp/records/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Erp Record */
        get: operations["get_erp_record_api_v1_erp_records__object_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Erp Record */
        patch: operations["update_erp_record_api_v1_erp_records__object_id__patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompanySettingsResponse */
        CompanySettingsResponse: {
            /** Id */
            id: number;
            /** Company Name */
            company_name: string;
            /** Legal Form */
            legal_form: string;
            /** Street */
            street: string | null;
            /** Street Nr */
            street_nr: string | null;
            /** Zip Code */
            zip_code: string | null;
            /** City */
            city: string | null;
            /** Country */
            country: string;
            /** Uid Number */
            uid_number: string | null;
            /** Vat Number */
            vat_number: string | null;
            /** Trade Register Nr */
            trade_register_nr: string | null;
            /** Trade Register Canton */
            trade_register_canton: string | null;
            /** Share Capital */
            share_capital: string | null;
            /** Iban Masked */
            iban_masked?: string | null;
            /** Qr Iban Masked */
            qr_iban_masked?: string | null;
            /** Bank */
            bank: string | null;
            /** Bic Swift */
            bic_swift: string | null;
            /** Email */
            email: string;
            /** Phone */
            phone: string | null;
            /** Website */
            website: string;
            /** Vat Method */
            vat_method: string;
            /** Vat Period */
            vat_period: string;
            /** Default Payment Days */
            default_payment_days: number;
            /** Default Skonto Pct */
            default_skonto_pct: string | null;
            /** Default Skonto Days */
            default_skonto_days: number | null;
            /** Oss Active */
            oss_active: boolean;
            /** Oss Reg Number */
            oss_reg_number: string | null;
            /** Vies Active */
            vies_active: boolean;
            /** Logo Path */
            logo_path: string | null;
            /** Stripe Publishable Key */
            stripe_publishable_key: string | null;
            /** Plausible Domain */
            plausible_domain: string | null;
            /** Hcaptcha Site Key */
            hcaptcha_site_key: string | null;
        };
        /** CompanySettingsUpdate */
        CompanySettingsUpdate: {
            /** Company Name */
            company_name?: string | null;
            /** Legal Form */
            legal_form?: string | null;
            /** Street */
            street?: string | null;
            /** Street Nr */
            street_nr?: string | null;
            /** Zip Code */
            zip_code?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /** Uid Number */
            uid_number?: string | null;
            /** Vat Number */
            vat_number?: string | null;
            /** Trade Register Nr */
            trade_register_nr?: string | null;
            /** Trade Register Canton */
            trade_register_canton?: string | null;
            /** Share Capital */
            share_capital?: string | null;
            /** Iban */
            iban?: string | null;
            /** Qr Iban */
            qr_iban?: string | null;
            /** Bank */
            bank?: string | null;
            /** Bic Swift */
            bic_swift?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
            /** Vat Method */
            vat_method?: string | null;
            /** Vat Period */
            vat_period?: string | null;
            /** Default Payment Days */
            default_payment_days?: number | null;
            /** Default Skonto Pct */
            default_skonto_pct?: number | string | null;
            /** Default Skonto Days */
            default_skonto_days?: number | null;
            /** Oss Active */
            oss_active?: boolean | null;
            /** Oss Reg Number */
            oss_reg_number?: string | null;
            /** Vies Active */
            vies_active?: boolean | null;
            /** Stripe Publishable Key */
            stripe_publishable_key?: string | null;
            /** Plausible Domain */
            plausible_domain?: string | null;
            /** Hcaptcha Site Key */
            hcaptcha_site_key?: string | null;
        };
        /** ContactRequest */
        ContactRequest: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Subject */
            subject: string;
            /** Message */
            message: string;
        };
        /**
         * ErpAdminUpdate
         * @description Fields an admin may change from the ERP panel.
         */
        ErpAdminUpdate: {
            /** Role */
            role?: string | null;
            /** Department */
            department?: string | null;
            /** Job Title */
            job_title?: string | null;
            /** Employment Start Date */
            employment_start_date?: string | null;
            /** Weekly Hours */
            weekly_hours?: number | string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** UserProfileResponse */
        UserProfileResponse: {
            /** Id */
            id: number;
            /** Object Id */
            object_id: number | null;
            /** Firebase Uid */
            firebase_uid: string;
            /** Email */
            email: string;
            /** Photo Url */
            photo_url: string | null;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Phone */
            phone: string | null;
            /** Address Line1 */
            address_line1: string | null;
            /** Address Line2 */
            address_line2: string | null;
            /** City */
            city: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** State Region */
            state_region: string | null;
            /** Country */
            country: string;
            /** Ship Name */
            ship_name: string | null;
            /** Ship Company */
            ship_company: string | null;
            /** Ship Address Line1 */
            ship_address_line1: string | null;
            /** Ship Address Line2 */
            ship_address_line2: string | null;
            /** Ship City */
            ship_city: string | null;
            /** Ship Postal Code */
            ship_postal_code: string | null;
            /** Ship State Region */
            ship_state_region: string | null;
            /** Ship Country */
            ship_country: string | null;
            /** Invoice Company */
            invoice_company: string | null;
            /** Invoice First Name */
            invoice_first_name: string | null;
            /** Invoice Last Name */
            invoice_last_name: string | null;
            /** Invoice Address Line1 */
            invoice_address_line1: string | null;
            /** Invoice Address Line2 */
            invoice_address_line2: string | null;
            /** Invoice City */
            invoice_city: string | null;
            /** Invoice Postal Code */
            invoice_postal_code: string | null;
            /** Invoice Country */
            invoice_country: string | null;
            /** Invoice Email */
            invoice_email: string | null;
            /** Invoice Same As Shipping */
            invoice_same_as_shipping: boolean;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Company Name */
            company_name: string | null;
            /** Uid Number */
            uid_number: string | null;
            /** Vat Number */
            vat_number: string | null;
            /** Vat Registered */
            vat_registered: boolean;
            /** Trade Register Nr */
            trade_register_nr: string | null;
            /** Trade Register Canton */
            trade_register_canton: string | null;
            /** Company Website */
            company_website: string | null;
            /** Company Billing Email */
            company_billing_email: string | null;
            /** Bank Account Holder */
            bank_account_holder: string | null;
            /** Bank Iban */
            bank_iban: string | null;
            /** Bank Bic */
            bank_bic: string | null;
            /** Bank Name */
            bank_name: string | null;
            /** Department */
            department: string | null;
            /** Job Title */
            job_title: string | null;
            /** Employment Start Date */
            employment_start_date: string | null;
            /** Weekly Hours */
            weekly_hours: string | null;
            /** Language */
            language: string;
            /** Notification Email */
            notification_email: boolean;
            /** Notification Inapp */
            notification_inapp: boolean;
            /** Newsletter Opt In */
            newsletter_opt_in: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /** Terms Accepted At */
            terms_accepted_at: string | null;
            /** Terms Version */
            terms_version: string | null;
        };
        /**
         * UserProfileUpdate
         * @description Self-service update — only fields a user may edit themselves.
         *     Employment/role fields are intentionally excluded; use ErpAdminUpdate for those.
         */
        UserProfileUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address Line1 */
            address_line1?: string | null;
            /** Address Line2 */
            address_line2?: string | null;
            /** City */
            city?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** State Region */
            state_region?: string | null;
            /** Country */
            country?: string | null;
            /** Invoice Company */
            invoice_company?: string | null;
            /** Invoice First Name */
            invoice_first_name?: string | null;
            /** Invoice Last Name */
            invoice_last_name?: string | null;
            /** Invoice Address Line1 */
            invoice_address_line1?: string | null;
            /** Invoice Address Line2 */
            invoice_address_line2?: string | null;
            /** Invoice City */
            invoice_city?: string | null;
            /** Invoice Postal Code */
            invoice_postal_code?: string | null;
            /** Invoice Country */
            invoice_country?: string | null;
            /** Invoice Email */
            invoice_email?: string | null;
            /** Invoice Same As Shipping */
            invoice_same_as_shipping?: boolean | null;
            /** Company Name */
            company_name?: string | null;
            /** Uid Number */
            uid_number?: string | null;
            /** Company Billing Email */
            company_billing_email?: string | null;
            /** Bank Account Holder */
            bank_account_holder?: string | null;
            /** Bank Iban */
            bank_iban?: string | null;
            /** Bank Bic */
            bank_bic?: string | null;
            /** Bank Name */
            bank_name?: string | null;
            /** Notification Email */
            notification_email?: boolean | null;
            /** Notification Inapp */
            notification_inapp?: boolean | null;
            /** Newsletter Opt In */
            newsletter_opt_in?: boolean | null;
        };
        /** UserRoleUpdate */
        UserRoleUpdate: {
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    debug_api_v1_debug_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    update_me_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_terms_api_v1_auth_terms_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    send_contact_api_v1_contact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_admin_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySettingsResponse"];
                };
            };
        };
    };
    update_settings_api_v1_admin_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanySettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_settings_api_v1_admin_settings_public_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"][];
                };
            };
        };
    };
    update_user_role_api_v1_admin_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_api_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_log_api_v1_admin_audit_log_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                table_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notifications_api_v1_admin_notifications_get: {
        parameters: {
            query?: {
                unread_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_notification_read_api_v1_admin_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_erp_records_api_v1_erp_records_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"][];
                };
            };
        };
    };
    get_erp_record_api_v1_erp_records__object_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_erp_record_api_v1_erp_records__object_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ErpAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
